name: push detection
on: workflow_dispatch

jobs:
  main-job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
